--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.58.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 26/04/2017 07:40:02 p.m.
-- Server version: 5.7.18-log
-- Client version: 4.1
--


--
-- Definition for database sistemajudicial
--
DROP DATABASE IF EXISTS sistemajudicial;
CREATE DATABASE sistemajudicial
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE sistemajudicial;

--
-- Definition for table juez
--
CREATE TABLE juez (
  id INT(11) NOT NULL AUTO_INCREMENT,
  cedula VARCHAR(15) DEFAULT NULL,
  nombre VARCHAR(50) DEFAULT NULL,
  apellidos VARCHAR(50) DEFAULT NULL,
  telefono VARCHAR(20) DEFAULT NULL,
  sala VARCHAR(20) DEFAULT NULL,
  usuario VARCHAR(20) DEFAULT NULL,
  clave VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table querellante
--
CREATE TABLE querellante (
  id INT(11) NOT NULL AUTO_INCREMENT,
  cedula VARCHAR(255) DEFAULT NULL,
  nombre VARCHAR(255) DEFAULT NULL,
  apellidos VARCHAR(255) DEFAULT NULL,
  telefono VARCHAR(255) DEFAULT NULL,
  direccion VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UK_quellerarte_id (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 12
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table caso
--
CREATE TABLE caso (
  id INT(11) NOT NULL AUTO_INCREMENT,
  descripcion VARCHAR(200) DEFAULT NULL,
  id_querellante INT(11) DEFAULT NULL,
  id_juez INT(11) DEFAULT NULL,
  estado VARCHAR(50) DEFAULT NULL,
  fecha DATE DEFAULT NULL,
  historial VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_caso_id_juez FOREIGN KEY (id_juez)
    REFERENCES juez(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_caso_id_querellante2 FOREIGN KEY (id_querellante)
    REFERENCES querellante(id) ON DELETE NO ACTION ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 58
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table juez
--
INSERT INTO juez(id, cedula, nombre, apellidos, telefono, sala, usuario, clave) VALUES
(1, '116810122', 'Gary', 'Valverde Hampton', '88882222', '1', 'garyvh2', '123'),
(2, '123456789', 'Diego', 'Vargas Aponte', '22228888', '2', 'diegova8', '123');

-- 
-- Dumping data for table querellante
--

-- Table sistemajudicial.querellante does not contain any data (it is empty)

-- 
-- Dumping data for table caso
--

-- Table sistemajudicial.caso does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;